version: "3.7"

services:
  postgres:
    container_name: 'PostgresSQL'
    image: "postgres:12"
    environment:
      POSTGRES_PASSWORD: "zaq1@WSX"
    volumes:
      - "/Users/maciejdybowski/postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf"
      - "/Users/maciejdybowski/postgres/data:/var/lib/postgresql/data:delegated"
    ports:
      - "5432:5432"