version: "3.0"

services:
  postgres:
    container_name: 'PostgresSQL'
    image: "postgres:12"
    environment:
      POSTGRES_PASSWORD: "zaq1@WSX"
    volumes:
      - "/Users/maciejdybowski/postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf"
      - "/Users/maciejdybowski/postgres/data:/var/lib/postgresql/data:delegated"
    ports:
      - "5432:5432"

  api:
    container_name: 'SpringApp'
    build: ./
    ports:
      - "8000:8080"
    depends_on:
      - postgres
